version: '3.9'

services:
  db_postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: qwe
      POSTGRES_USER: postgres
      POSTGRES_DB: zadanie13_docker
    ports:
      - 5476:5432
    volumes:
      - pgdataToDoList:/var/lib/postgresql/data
    restart: always
    container_name: db_postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes:
  pgdataToDoList: