port = ":3000"
database_url = "user=postgres password=qwe host=localhost dbname=db_golang sslmode=disable"

RABBITMQ_URL = "amqp://guest:guest@localhost:5672"

RABBITMQ_TASKFIELDVALUE_QUEUE = "taskfieldvalue_queue"